# Generated by Django 4.0.5 on 2022-06-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpart',
            name='price',
        ),
        migrations.AddField(
            model_name='carpart',
            name='price2',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
