# Generated by Django 4.0.5 on 2022-06-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_carpart_price_carpart_price2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpart',
            old_name='price2',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='carpart',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='part',
            field=models.ManyToManyField(to='core.carpart'),
        ),
    ]
